### ISSUE TITLE
QUESTION: Relation Hekate FSharp.FGL

### ISSUE THREAD

**Issue by WalternativE** [CSBiology/FSharp.FGL#1]
### Description

I'm currently researching functional graph libraries for a project I am working on. On the FSharp side of things I found FSharp.FGL as well as Hekate - both oriented on the Haskell FGL library. Inspecting the source code I found a lot of similarities between the two projects - is FSharp.FGL a spin-off or fork of Heakte or in any other way related to this project?

Regards

**Comment by HLWeil** [comment]
Hey Gregor! Thanks for your interest.

The implementation of FSharp.FGL is based on Hekate. So most things that seem identical are taken from there. The reason for this is that I liked their take on the FGL but wanted some major tweeks for my own use (E.g. naming and specialized functions for directed or undirected graphs). Also there are some bigger changes planned.
I hope this answers your question satisfyingly.

Regards
Lukas

**Comment by WalternativE** [comment]
Hi Lukas.

Thanks for answering my question. It is clearer now, thank you. I'd have other questions regarding the project infrastructure - should I open a new detailed ticket for that or should I ask it here?

Regards
Gregor

**Comment by HLWeil** [comment]
Yes opening a new isse is better.

**Comment by WalternativE** [comment]
Good - I'll do that and close this issue.
