### ISSUE TITLE
Vertices module moved into the Graph module

### ISSUE THREAD

**Issue by Evelios** [CSBiology/FSharp.FGL#28]
The example code on the [FSharp.FGL Documentation Homepage](../blob/developer/docs/content/index.fsx#L19) is out of date.

```fs
#r "FSharp.FGL.dll"
open FSharp.FGL 

Graph.empty
|> Undirected.Vertices.addMany [(1,"Look At Me Im VertexOne");(2,"Look At Me Im VertexTwo")]
|> Undirected.Edges.add (1,2,"Im An Edge Between VertexOne And VertexTwo ")
|> Undirected.Edges.tryFind 1 2
//Returns Some (1,2,"Im An Edge Between VertexOne And VertexTwo ")
```

This code for adding vertices was moved from the `Undirected` and `Directed` modules to the `Graph` module in d015d7fe0e91231447d7a9c7a8d685a1859839af

```fs
/// Should change
Graph.empty
|> Undirected.Vertices.addMany [(1,"Look At Me Im VertexOne");(2,"Look At Me Im VertexTwo")]

/// To
Graph.empty
|> Vertices.addMany [(1,"Look At Me Im VertexOne");(2,"Look At Me Im VertexTwo")]
```

I also found an example on the page for [Working with FSharp.FGL](../blob/developer/docs/content/newgraph.fsx#L48) which has the proper working example.

**Comment by HLWeil** [comment]
Hey, thank you for pointing that out =) 
If you want you could open up a PR?

The files used for building the docs are found in https://github.com/CSBiology/FSharp.FGL/tree/developer/docs/content

**Comment by LibraChris** [comment]
Thanks again for pointing that out. I fixed this issue in the update for the library structure #35.
