### ISSUE TITLE
[BUG] Directed graph: decompose only removes outgoing edges

### ISSUE THREAD

**Issue by 7enderhead** [CSBiology/FSharp.FGL#43]
**Describe the bug**
On removing a vertex from a directed graph with `decompose`, only edges going out from the vertex are removed in the resulting graph. Edges leading to the removed vertex from its 'parents' remain in the graph and lead to a non-existing vertex.

**To Reproduce**
dotnet fsi example for simple directed graph `"1" -> "2" -> "3"`:
```
> g |> Edges.toEdgeList;;
val it : LEdge<string,unit> list = [("1", "2", ()); ("2", "3", ())]

> g |> decompose "2" |> snd |> Edges.toEdgeList;;
val it : LEdge<string,unit> list = [("1", "2", ())]
```

**Expected behavior**
Edges `1 -> 2` and `2 -> 3` should be removed. Edge `1 -> 2` remains.

**OS and framework information (please complete the following information):**
 - OS: Linux 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- .Net core SDK version: 5.0.202

**Comment by LibraChris** [comment]
Hey,
thank you for bringing this to our attention. We are working on a solution to the problem and will release a fix as soon as possible.

**Comment by LibraChris** [comment]
I have applied the bugfix. Thank you again for pointing it out.
