### ISSUE TITLE
Module structure and code duplication

### ISSUE THREAD

**Issue by WalternativE** [CSBiology/FSharp.FGL#6]
### Description

Currently there is the `FSharp.FGL` namespace and its general `Graph` submodule as well as the directed and undirected namespaces with their respective submodules. A subset of functionality like the `iter` and `map` operations don't seem connected to the direction the graph has and should work on all graphs (in fact the implementations tend to be the same).

I don't know if it has still room in this issue but while talking about module structure I'd also like to discuss the possible usage of the `RequireQualifiedAccessAttribute` (https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/core.requirequalifiedaccessattribute-class-%5Bfsharp%5D). I don't know how often it happens in day to day usage of the library but it seems to me that name clashes could inadvertently happen in a larger analysis. I don't have the same experience as you do - so it is not unlikely that I'm totally wrong with this. What do you think?

**Comment by HLWeil** [comment]
The duplication of the submodule and function names is intended to make working with directed or undirected Graphs analogical. There would definitely be problems if both namespaces (directed and undirected) are opened but I trust the user to only open one and call functions of the other explicititly (if even needed). Requiring explicit names all the time would make working with the library way too clumsy IMO. 
Regarding the duplicate implementation of Vertices.iter and Vertices.map: This could be done both ways. I'd say it's okay for those 2 functions to be duplicate to keep the general structure consistent. Do you agree? It's definitely debatable if not.

**Comment by WalternativE** [comment]
The duplication of the submodule names in the directed and undirected modules is generally a good idea imho. I just don't know if functions that work generally on all graphs should be hard copied. An opiton to get rid of the copies to have private versions of the algorithms in the general module and use them for the directed/undirected submodules to offer an easy API. Do you see problems with that?

Would also make it easy to diverge for a couple of algorithms whenever the properties of an undirected or directed graph make it possible to optimize internally. It's kind of already done with the usage of a Map as the underlying datatype for the Graph type - it's further away from the original FGL implementation but afaik more performant. What do you think?

**Comment by HLWeil** [comment]
I removed the code duplication you mentioned in d015d7fe0e91231447d7a9c7a8d685a1859839af

With this I'll close this issue.
