### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by WalternativE** [CSBiology/FSharp.FGL#8]
### Description

Clients are used to get their libraries distributed as nuget packages. I think it would be sensible to offer FGL as one. Before releasing something stable we could offer it as a -pre package which should signal the current instability of the project. As discussed in #2 offering a netstandard2.0 packae should be enough.

**Comment by gilmishal** [comment]
Any update?

**Comment by kMutagene** [comment]
Although @HLWeil should verify this, I think the way to go is the following:
 - [ ] 1. Update the project to the latest [project Scaffold layout](https://github.com/fsprojects/ProjectScaffold)(this is mainly for documentation and FAKE5)
 - [ ] 2. Add appveyor and travis build tests. I did this for our other projects and can do this after 1. is done. 
 - [ ] 3. As long as the project is in the state @WalternativE indicated, offer a nuget package over a branch called nuget. example can be seen [here](https://github.com/CSBiology/FSharp.Stats/tree/nuget). You can easily get these packages with [paket](https://fsprojects.github.io/Paket/git-dependencies.html#Using-Git-repositories-as-NuGet-source).

**Comment by HLWeil** [comment]
Yes this is the way to go. In order for this project to be released on nuget, there are some changes needed, especially the addition of tests. 

If I see correctly @kMutagene , you already finished step 1 in 0fee5bbc4634a86f31c7471745d2dd092a414790 and 333ff698ef405ca670a647360ff6d59f6f22f861? 

Building that branch works fine. How about you merge it into the developer branch and we continue from there?

**Comment by kMutagene** [comment]
Good catch, seems like i forgot to merge that into the master branch. I will take care of that, adapt the build script, and create the nuget branch in the next few days. I suggest you create a release milestone and issues for the stuff that has to be done in order  to reach it.

**Comment by kMutagene** [comment]
1 and 2 done: 20f608caeb646bd2e0a2569840eac0021aa53059 , fdbc0ce56772f78dbe5bb7eb3c7f50bcd701a304 , 0fee5bbc4634a86f31c7471745d2dd092a414790 .

@HLWeil , the only thing left to do is to create an empty nuget branch, merge developer into master, and run the GitReleaseNuget target from master.

**Comment by kMutagene** [comment]
@gilmishal Prerelease package available on the nuget branch: https://github.com/CSBiology/FSharp.FGL/tree/nuget

**Comment by HLWeil** [comment]
The nuget package is now available at https://www.nuget.org/packages/FSharp.FGL/0.0.1
